#!/usr/bin/env sh

set -e

if [ -z "$1" ]; then
	echo "Use vga or lvds as a argument."
	exit 1
fi

case "$1" in
	"vga"      )
		xrandr --output VGA-1 --primary --mode 1920x1080;;
	"lvds" | * )
		xrandr --output LVDS-1 --primary --mode 1366x768;;
esac

