#!/usr/bin/env sh

set -e

if [ -z "$1" ]; then
	echo "Use vga or lvds as a argument."
	exit 1
fi

case "$1" in
	"vga"      )
		xrandr --output VGA-1 --auto --output LVDS-1 --off;;
	"lvds" | * )
		xrandr --output LVDS-1 --auto --output VGA-1 --off;;
esac

