#!/usr/bin/env sh

set -e

if [ -z "$1" ]; then
    echo "Specify network or channel"
    exit 1
fi

libera () {
    SERVER=irc.libera.chat
    PORT=6665
}

oftc () {
    SERVER=irc.oftc.net
    PORT=6667
}

case $1 in "libera")
    libera;;
"oftc")
    oftc;;
"suckless")
    oftc
    CHANNEL="#suckless";;
"openbsd")
    libera
    CHANNEL="#openbsd";;
*)
    echo "Unknown network or channel: $1"
    exit 1;;
esac

PASS=$(pass irc/password)
NICK=kon4ru

COMMAND="-s $SERVER -p $PORT -n $NICK"
if [ ! -z "$CHANNEL" ]; then
    COMMAND="$COMMAND -c $CHANNEL"
fi
COMMAND="$COMMAND -x"

kirc $COMMAND <<END
privmsg NickServ :identify $PASS
END
