#!/usr/bin/env sh

set -euo pipefail

DIR=~/data/irc
USER=kon4ru
PASS=$(pass /irc/password)

cd $DIR
ii -s irc.libera.chat -p 6665 -i $DIR -n kon4ru -k PASS &

sleep 5

echo "/j nickserv IDENTIFY $USER $PASS" >> irc.libera.chat/in
echo "/j #openbsd" >> irc.libera.chat/in
echo "started"
