# -*- mode: sh -*-

. ~/.profile

alias reload='. ~/.config/ksh/kshrc'
alias esh='$EDITOR ~/.config/ksh/kshrc'

set -o emacs
HISTCONTROL=ignoredups:ignorespace
HISTSIZE=1000
HISTFILE=$HOME/.ksh_history
PS1='${USER}@\h:\W\$ '

alias cvsupdate='cvs -q up -Pd -A'
alias cvsdiff='cvs diff -uNp'
alias cvsrestore='cvs update -C'

whatabout () {
    $PAGER "/usr/local/share/doc/pkg-readmes/$1"
}
set -A complete_whatabout -- $(ls /usr/local/share/doc/pkg-readmes/)

# autocomplete
set -A complete_git -- pull push clone checkout status commit clean restore diff
set -A complete_sttemp -- $(sttemp -l)
set -A complete_pkg_delete -- $(pkg_info | awk "{print \$1}")

# agenda
calendar
